# Generated by Django 5.2.3 on 2025-06-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='opening_hours',
        ),
    ]
