# Generated by Django 5.2.3 on 2025-06-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_library_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='library_app.library'),
        ),
    ]
